config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :inventories
  resources :items
  resources :peples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: :json} do
   namespace :v1 do
        resources :inventories
        resources :peples
        resources :items
        resources :transfers
   end
  end

end

app/models/peple.rb
class Peple < ApplicationRecord
end

app/controllers/api/v1/peples_controller.rb
class Api::V1::PeplesController < ApplicationController
  before_action :set_peple, only: [:show, :edit, :update, :destroy]
skip_before_filter  :verify_authenticity_token
  # GET /peples
  def index
    @peples = Peple.all
    render :json => @peples
  end

  # GET /peples/1
  def show
  end

  # GET /peples/new
  def new
    @peple = Peple.new
  end

  # GET /peples/1/edit
  def edit
  end

  # POST /peples
  def create
    @peple = Peple.new(peple_params)

    if @peple.save
      render json: @peple, status: 201
    else
      render json: { errors: @peple.errors}, status: 422
    end
  end

  # PATCH/PUT /peples/1
  def update
    if @peple.update(peple_params)
      render json: @peple, status: 200
     else
       render json: { errors: @peple.errors }, status: 422
    end
  end

  # DELETE /peples/1
  def destroy
    @peple.destroy
    head 204
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peple
      @peple = Peple.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def peple_params
      params.require(:peple).permit(:name, :gender, :infected, :age, :longitude, :latitude)
    end
end

app/controllers/peples_controller.rb
class PeplesController < ApplicationController
  before_action :set_peple, only: [:show, :edit, :update, :destroy]

  # GET /peples
  def index
    @peples = Peple.all
  end

  # GET /peples/1
  def show
  end

  # GET /peples/new
  def new
    @peple = Peple.new
  end

  # GET /peples/1/edit
  def edit
  end

  # POST /peples
  def create
    @peple = Peple.new(peple_params)

    if @peple.save
      redirect_to @peple, notice: 'Peple was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /peples/1
  def update
    if @peple.update(peple_params)
      redirect_to @peple, notice: 'Peple was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /peples/1
  def destroy
    @peple.destroy
    redirect_to peples_url, notice: 'Peple was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peple
      @peple = Peple.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def peple_params
      params.require(:peple).permit(:name, :gender, :infected, :age, :longitude, :latitude)
    end
end

app/helpers/peples_helper.rb
module PeplesHelper
end

app/views/peples/_form.html.erb
<%= form_for(peple) do |f| %>
  <% if peple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peple.errors.count, "error") %> prohibited this peple from being saved:</h2>

      <ul>
      <% peple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :infected %>
    <%= f.check_box :infected %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peples/edit.html.erb
<h1>Editing Peple</h1>

<%= render 'form', peple: @peple %>

<%= link_to 'Show', @peple %> |
<%= link_to 'Back', peples_path %>

app/views/peples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peples</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Infected</th>
      <th>Age</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peples.each do |peple| %>
      <tr>
        <td><%= peple.name %></td>
        <td><%= peple.gender %></td>
        <td><%= peple.infected %></td>
        <td><%= peple.age %></td>
        <td><%= peple.longitude %></td>
        <td><%= peple.latitude %></td>
        <td><%= link_to 'Show', peple %></td>
        <td><%= link_to 'Edit', edit_peple_path(peple) %></td>
        <td><%= link_to 'Destroy', peple, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peple', new_peple_path %>

app/views/peples/new.html.erb
<h1>New Peple</h1>

<%= render 'form', peple: @peple %>

<%= link_to 'Back', peples_path %>

app/views/peples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @peple.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @peple.gender %>
</p>

<p>
  <strong>Infected:</strong>
  <%= @peple.infected %>
</p>

<p>
  <strong>Age:</strong>
  <%= @peple.age %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @peple.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @peple.latitude %>
</p>

<%= link_to 'Edit', edit_peple_path(@peple) %> |
<%= link_to 'Back', peples_path %>