config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :inventories
  resources :items
  resources :peples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: :json} do
   namespace :v1 do
        resources :inventories
        resources :peples
        resources :items
        resources :transfers
   end
  end

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :peple
  belongs_to :item
end

app/controllers/api/v1/inventories_controller.rb
class Api::V1::InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token
  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
    render :json => @inventories
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    @inventory.points = @inventory.quantity * @inventory.item.points

    if @inventory.save
      render json: @inventory, status: 201
    else
      render json: { errors: @inventory.errors}, status: 422
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    if @inventory.update(inventory_params)
     render json: @inventory, status: 200
     else
       render json: { errors: @inventory.errors }, status: 422
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    head 204
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:peple_id, :item_id, :quantity)
    end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:peple_id, :item_id, :quantity, :points)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(inventory) do |f| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :peple_id %>
    <%= f.text_field :peple_id %>
  </div>

  <div class="field">
    <%= f.label :item_id %>
    <%= f.text_field :item_id %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Peple</th>
      <th>Item</th>
      <th>Quantity</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.peple %></td>
        <td><%= inventory.item %></td>
        <td><%= inventory.quantity %></td>
        <td><%= inventory.points %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Peple:</strong>
  <%= @inventory.peple %>
</p>

<p>
  <strong>Item:</strong>
  <%= @inventory.item %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @inventory.quantity %>
</p>

<p>
  <strong>Points:</strong>
  <%= @inventory.points %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>