config/routes.rb
Rails.application.routes.draw do
  resources :transfers
  resources :inventories
  resources :items
  resources :peples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: {format: :json} do
   namespace :v1 do
        resources :inventories
        resources :peples
        resources :items
        resources :transfers
   end
  end

end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :peple1, :class_name => "PepleModel"
  belongs_to :item1, :class_name => "ItemModel"
  belongs_to :peple2, :class_name => "PepleModel"
  belongs_to :item2, :class_name => "ItemModel"
end

app/controllers/api/v1/transfers_controller.rb
class Api::V1::TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
    render :json => @transfers
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    if is_infected(@transfer.peple1, @transfer.peple2) == false
      render json: { errors: @transfer.errors}, status: 422
    else
      @bag1 = find_bag(@transfer.peple1)
      @bag2 = find_bag(@transfer.peple2)
      @items1 = @bag.where(items_id: @transfer.items1)
      @items2 = @bag.where(items_id: @transfer.items2)
      if @items2.points == @items1.points
         @bag1.peple_id = @transfer.peple2
         @bag1.save
         @bag2.peple_id = @transfer.peple1
         @bag2.save
         @transfer.save
          render json: @transfer, status: 201
      else
         ender json: { errors: @transfer.errors}, status: 422
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
      if @transfer.update(transfer_params)
        render json: @transfer, status: 200
      else
        render json: { errors: @transfer.errors }, status: 422
      end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    head 204
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:peple1_id, :item1_id, :quantity1, :peple2_id, :item2_id, :quantity)
    end

    def is_infected( peple1, peple2)
      peple1 = Peple.where(id: peple1)
      peple2 = Peple.where(id: peple2)
      if peple1.infected == true || peple2.infected == true
         return false
      else
         return true
      end
    end

    def find_bag(person)
      id_person = person
      return Inventory.where(peple_id:  id_person)
   end

end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:peple1_id, :item1_id, :quantity1, :peple2_id, :item2_id, :quantity)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for(transfer) do |f| %>
  <% if transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :peple1_id %>
    <%= f.text_field :peple1_id %>
  </div>

  <div class="field">
    <%= f.label :item1_id %>
    <%= f.text_field :item1_id %>
  </div>

  <div class="field">
    <%= f.label :quantity1 %>
    <%= f.number_field :quantity1 %>
  </div>

  <div class="field">
    <%= f.label :peple2_id %>
    <%= f.text_field :peple2_id %>
  </div>

  <div class="field">
    <%= f.label :item2_id %>
    <%= f.text_field :item2_id %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfers</h1>

<table>
  <thead>
    <tr>
      <th>Peple1</th>
      <th>Item1</th>
      <th>Quantity1</th>
      <th>Peple2</th>
      <th>Item2</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.peple1 %></td>
        <td><%= transfer.item1 %></td>
        <td><%= transfer.quantity1 %></td>
        <td><%= transfer.peple2 %></td>
        <td><%= transfer.item2 %></td>
        <td><%= transfer.quantity %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form', transfer: @transfer %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Peple1:</strong>
  <%= @transfer.peple1 %>
</p>

<p>
  <strong>Item1:</strong>
  <%= @transfer.item1 %>
</p>

<p>
  <strong>Quantity1:</strong>
  <%= @transfer.quantity1 %>
</p>

<p>
  <strong>Peple2:</strong>
  <%= @transfer.peple2 %>
</p>

<p>
  <strong>Item2:</strong>
  <%= @transfer.item2 %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @transfer.quantity %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>